# Generated by Django 5.1.5 on 2025-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('course', models.CharField(choices=[('math', 'Mathematics'), ('sci', 'Science'), ('eng', 'Engineering'), ('art', 'Arts')], max_length=50)),
            ],
        ),
    ]
